const BOOKEDAPPOINTMENT='BookedAppointment'
const GETALLDOCTORS='GetAllDoctors'
const SETSELECTEDDATE="SetSelectedDate"
const SETREGISTRATIONDATA="SETREGISTRATIONDATA"
const SETLOGINDATA="SETLOGINDATA"




export {
    BOOKEDAPPOINTMENT,
    GETALLDOCTORS,
    SETSELECTEDDATE,
    SETREGISTRATIONDATA,
    SETLOGINDATA
  }